/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-06-26 14:54:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.gestion_002dcandidatos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gestion_002dcandidatos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gestión de Candidatos Electoral</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var contextPath = \"${pageContext.request.contextPath}\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"../gestion-candidatos/AñadirCandidato.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<header class=\"header-primary\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container-fluid px-4\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"dashboard.html\">\r\n");
      out.write("                <i class=\"fas fa-th-large me-3\"></i>\r\n");
      out.write("                Panel Administrative Electoral\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"d-flex align-items-center gap-3 text-white font-monospace text-end d-none d-md-block\" style=\"font-size: 0.85rem;\">\r\n");
      out.write("                <div>Supervisor Electoral</div>\r\n");
      out.write("                <div class=\"text-white-50\">DNI: 99999999</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main-content py-4\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("            <a href=\"dashboard.html\" class=\"btn btn-outline-primary btn-sm rounded-2 px-3\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left me-2\"></i> VOLVER AL DASHBOARD\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1 class=\"h3 mb-1 fw-bold text-dark\">Gestión de Candidatos</h1>\r\n");
      out.write("                <p class=\"text-muted mb-0\" style=\"font-size: 0.9rem;\">Administre los candidatos que aparecerán en la boleta electoral</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"btn btn-primary px-4 fw-medium shadow-sm d-inline-flex align-items-center rounded-3\" data-bs-toggle=\"modal\" data-bs-target=\"#modalCandidato\" onclick=\"prepararModalAgregar()\">\r\n");
      out.write("                <i class=\"fas fa-plus me-2\"></i> AGREGAR CANDIDATO\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card border-0 shadow-sm rounded-4 p-4 mb-4 bg-white\">\r\n");
      out.write("            <div class=\"d-flex flex-column gap-4\" id=\"contenedor-candidatos\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"modalCandidato\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" style=\"max-width: 480px;\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow-lg rounded-3 p-4 bg-white\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-header border-0 p-0 mb-4\">\r\n");
      out.write("                <h4 class=\"modal-title fw-bold text-dark\" id=\"modalCandidatoLabel\" style=\"font-size: 1.3rem;\">Agregar Nuevo Candidato</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-body p-0 mb-4\">\r\n");
      out.write("                <form id=\"formCandidato\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"candidatoId\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control px-3 py-2.5 border rounded\" id=\"nombreCompleto\" placeholder=\"Nombre del Candidato\" style=\"font-size: 0.95rem;\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control px-3 py-2.5 border rounded\" id=\"partido\" placeholder=\"Partido Político\" style=\"font-size: 0.95rem;\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-1 d-flex align-items-center gap-3 p-2 border rounded bg-light-subtle\">\r\n");
      out.write("                        <label for=\"colorPartido\" class=\"form-label mb-0 text-muted ps-1\" style=\"font-size: 0.9rem;\">Color identificador:</label>\r\n");
      out.write("                        <input type=\"color\" class=\"form-control form-control-color border-0 rounded-circle\" id=\"colorPartido\" value=\"#2563eb\" style=\"width: 38px; height: 38px; cursor: pointer;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"text-muted d-block ps-1\" style=\"font-size: 0.75rem;\">Color asignado para gráficos estadísticos y boleta</small>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-footer border-0 p-0 d-flex justify-content-end gap-3\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link text-decoration-none fw-semibold text-primary px-2\" data-bs-dismiss=\"modal\" style=\"font-size: 0.88rem; letter-spacing: 0.5px;\">CANCELAR</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn px-4 py-2 fw-semibold border-0 text-muted rounded shadow-sm\" id=\"btnGuardarCandidato\" style=\"background-color: #e0e0e0; font-size: 0.88rem; letter-spacing: 0.5px;\">AGREGAR CANDIDATO</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Intenta recuperar los datos del localStorage; si no existen, inicializa la lista por defecto\r\n");
      out.write("let listaCandidatosBD = JSON.parse(localStorage.getItem('listaCandidatos')) || [\r\n");
      out.write("    { id: 1, nombreCompleto: \"María Rodríguez\", partido: \"Partido Progresista\", colorPartido: \"#2563eb\", votos: 203 },\r\n");
      out.write("    { id: 2, nombreCompleto: \"Carlos Fernández\", partido: \"Unión Nacional\", colorPartido: \"#dc2626\", votos: 187 },\r\n");
      out.write("    { id: 3, nombreCompleto: \"Ana Martínez\", partido: \"Frente del Pueblo\", colorPartido: \"#16a34a\", votos: 133 }\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("let bootstrapModal;\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("    bootstrapModal = new bootstrap.Modal(document.getElementById('modalCandidato'));\r\n");
      out.write("    renderizarListaCandidatos();\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('btnGuardarCandidato').addEventListener('click', guardarCandidato);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Función auxiliar para actualizar el almacenamiento local del navegador\r\n");
      out.write("function actualizarAlmacenamiento() {\r\n");
      out.write("    localStorage.setItem('listaCandidatos', JSON.stringify(listaCandidatosBD));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function renderizarListaCandidatos() {\r\n");
      out.write("    const contenedor = document.getElementById('contenedor-candidatos');\r\n");
      out.write("    if (!contenedor) return;\r\n");
      out.write("    \r\n");
      out.write("    contenedor.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("    if (listaCandidatosBD.length === 0) {\r\n");
      out.write("        contenedor.innerHTML = `<div class=\"text-center py-4 text-muted\">No hay candidatos registrados en la boleta electoral.</div>`;\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    listaCandidatosBD.forEach((candidato, index) => {\r\n");
      out.write("        const esUltimo = index === listaCandidatosBD.length - 1 ? \"\" : \"border-bottom pb-4\";\r\n");
      out.write("        \r\n");
      out.write("        const filaHtml = `\r\n");
      out.write("            <div class=\"row align-items-center ${esUltimo} g-3\">\r\n");
      out.write("                <div class=\"col-12 col-md-9 d-flex align-items-center gap-4\">\r\n");
      out.write("                    <div class=\"rounded-circle d-flex align-items-center justify-content-center text-white fw-bold shadow-sm\" \r\n");
      out.write("                         style=\"background-color: ${candidato.colorPartido}; width: 48px; height: 48px; min-width: 48px; font-size: 1.2rem;\">\r\n");
      out.write("                        ${candidato.nombreCompleto.charAt(0)}\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h5 class=\"mb-0 fw-bold text-dark\" style=\"font-size: 1.1rem;\">#${index + 1} ${candidato.nombreCompleto}</h5>\r\n");
      out.write("                        <div class=\"text-muted mt-1\" style=\"font-size: 0.85rem;\">\r\n");
      out.write("                            <span class=\"me-3\">Partido: <strong class=\"text-dark\">${candidato.partido}</strong></span>\r\n");
      out.write("                            <span class=\"me-3\">Color: <code class=\"px-2 py-0.5 rounded text-dark\" style=\"background-color: #f1f5f9;\">${candidato.colorPartido}</code></span>\r\n");
      out.write("                            <span>Votos: <strong class=\"text-dark\">${candidato.votos}</strong></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-md-3 d-flex justify-content-md-end justify-content-start align-items-center\">\r\n");
      out.write("                    <div class=\"d-flex gap-2\">\r\n");
      out.write("                        <button class=\"btn btn-light btn-sm text-primary rounded-2 px-3 fw-medium border\" onclick=\"prepararModalEditar(${candidato.id})\" title=\"Editar Candidato\">\r\n");
      out.write("                            <i class=\"fas fa-edit me-1\"></i> Editar\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"btn btn-light btn-sm text-danger rounded-2 px-3 fw-medium border\" onclick=\"eliminarCandidato(${candidato.id})\" title=\"Eliminar Candidato\">\r\n");
      out.write("                            <i class=\"fas fa-trash-alt me-1\"></i> Eliminar\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("        contenedor.insertAdjacentHTML('beforeend', filaHtml);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function prepararModalAgregar() {\r\n");
      out.write("    document.getElementById('modalCandidatoLabel').innerText = \"Agregar Nuevo Candidato\";\r\n");
      out.write("    \r\n");
      out.write("    const btnGuardar = document.getElementById('btnGuardarCandidato');\r\n");
      out.write("    btnGuardar.innerText = \"AGREGAR CANDIDATO\";\r\n");
      out.write("    btnGuardar.className = \"btn px-4 py-2 fw-semibold border-0 text-muted rounded shadow-sm\";\r\n");
      out.write("    btnGuardar.style.backgroundColor = \"#e0e0e0\"; \r\n");
      out.write("    btnGuardar.style.color = \"\";\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('formCandidato').reset();\r\n");
      out.write("    document.getElementById('candidatoId').value = \"\"; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function prepararModalEditar(id) {\r\n");
      out.write("    const candidato = listaCandidatosBD.find(c => c.id === id);\r\n");
      out.write("    \r\n");
      out.write("    if (candidato) {\r\n");
      out.write("        document.getElementById('modalCandidatoLabel').innerText = \"Modificar Candidato\";\r\n");
      out.write("        \r\n");
      out.write("        const btnGuardar = document.getElementById('btnGuardarCandidato');\r\n");
      out.write("        btnGuardar.innerText = \"MODIFICAR CANDIDATO\";\r\n");
      out.write("        btnGuardar.className = \"btn px-4 py-2 fw-semibold border-0 text-white rounded shadow-sm btn-primary\";\r\n");
      out.write("        btnGuardar.style.backgroundColor = \"\"; \r\n");
      out.write("\r\n");
      out.write("        document.getElementById('candidatoId').value = candidato.id;\r\n");
      out.write("        document.getElementById('nombreCompleto').value = candidato.nombreCompleto;\r\n");
      out.write("        document.getElementById('partido').value = candidato.partido;\r\n");
      out.write("        document.getElementById('colorPartido').value = candidato.colorPartido;\r\n");
      out.write("        \r\n");
      out.write("        bootstrapModal.show();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function guardarCandidato() {\r\n");
      out.write("    const id = document.getElementById('candidatoId').value;\r\n");
      out.write("    const nombreCompleto = document.getElementById('nombreCompleto').value.trim();\r\n");
      out.write("    const partido = document.getElementById('partido').value.trim();\r\n");
      out.write("    const colorPartido = document.getElementById('colorPartido').value;\r\n");
      out.write("\r\n");
      out.write("    if (!nombreCompleto || !partido) {\r\n");
      out.write("        alert(\"Por favor, complete todos los campos de información.\");\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (id === \"\") {\r\n");
      out.write("        listaCandidatosBD.push({\r\n");
      out.write("            id: Date.now(),\r\n");
      out.write("            nombreCompleto: nombreCompleto,\r\n");
      out.write("            partido: partido,\r\n");
      out.write("            colorPartido: colorPartido,\r\n");
      out.write("            votos: 0\r\n");
      out.write("        });\r\n");
      out.write("    } else {\r\n");
      out.write("        const index = listaCandidatosBD.findIndex(c => c.id == id);\r\n");
      out.write("        if (index !== -1) {\r\n");
      out.write("            listaCandidatosBD[index].nombreCompleto = nombreCompleto;\r\n");
      out.write("            listaCandidatosBD[index].partido = partido;\r\n");
      out.write("            listaCandidatosBD[index].colorPartido = colorPartido;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    actualizarAlmacenamiento(); // Guarda el estado actual de la lista\r\n");
      out.write("    bootstrapModal.hide();\r\n");
      out.write("    renderizarListaCandidatos();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function eliminarCandidato(id) {\r\n");
      out.write("    if (confirm(\"¿Está seguro de que desea eliminar este candidato de la boleta electoral?\")) {\r\n");
      out.write("        listaCandidatosBD = listaCandidatosBD.filter(c => c.id !== id);\r\n");
      out.write("        actualizarAlmacenamiento(); // Sincroniza la eliminación en el disco\r\n");
      out.write("        renderizarListaCandidatos();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
