/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-06-28 01:27:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.gestion_002dcandidatos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gestion_002dcandidatos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gestión de Candidatos Electoral</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Style.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        var contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<header class=\"header-primary\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container-fluid px-4\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard/dashboard.jsp\">\r\n");
      out.write("                <i class=\"fas fa-th-large me-3\"></i> Panel Administrativo Electoral\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main-content py-4\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard/dashboard.jsp\" class=\"btn btn-outline-primary btn-sm rounded-2 px-3\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left me-2\"></i> VOLVER AL DASHBOARD\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1 class=\"h3 mb-1 fw-bold text-dark\">Gestión de Candidatos</h1>\r\n");
      out.write("                <p class=\"text-muted mb-0\" style=\"font-size: 0.9rem;\">Administre los candidatos que aparecerán en la boleta electoral</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"btn btn-primary px-4 fw-medium shadow-sm d-inline-flex align-items-center rounded-3\" data-bs-toggle=\"modal\" data-bs-target=\"#modalCandidato\" onclick=\"prepararModalAgregar()\">\r\n");
      out.write("                <i class=\"fas fa-plus me-2\"></i> AGREGAR CANDIDATO\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card border-0 shadow-sm rounded-4 p-4 mb-4 bg-white\">\r\n");
      out.write("            <div class=\"d-flex flex-column gap-4\" id=\"contenedor-candidatos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"modalCandidato\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" style=\"max-width: 480px;\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow-lg rounded-3 p-4 bg-white\">\r\n");
      out.write("            <div class=\"modal-header border-0 p-0 mb-4\">\r\n");
      out.write("                <h4 class=\"modal-title fw-bold text-dark\" id=\"modalCandidatoLabel\" style=\"font-size: 1.3rem;\">Agregar Nuevo Candidato</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body p-0 mb-4\">\r\n");
      out.write("                <form id=\"formCandidato\" onsubmit=\"return false;\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"candidatoId\">\r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control px-3 py-2.5 border rounded\" id=\"nombreCompleto\" placeholder=\"Nombre del Candidato\" required autocomplete=\"off\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control px-3 py-2.5 border rounded\" id=\"partido\" placeholder=\"Partido Político\" required autocomplete=\"off\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1 d-flex align-items-center gap-3 p-2 border rounded bg-light-subtle\">\r\n");
      out.write("                        <label for=\"colorPartido\" class=\"form-label mb-0 text-muted ps-1\" style=\"font-size: 0.9rem;\">Color identificador:</label>\r\n");
      out.write("                        <input type=\"color\" class=\"form-control form-control-color border-0 rounded-circle\" id=\"colorPartido\" value=\"#2563eb\" style=\"width: 38px; height: 38px; cursor: pointer;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0 p-0 d-flex justify-content-end gap-3\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link text-decoration-none fw-semibold text-primary px-2\" data-bs-dismiss=\"modal\">CANCELAR</button>\r\n");
      out.write("                <button type=\"submit\" form=\"formCandidato\" class=\"btn px-4 py-2 fw-semibold border-0 text-muted rounded shadow-sm\" id=\"btnGuardarCandidato\" style=\"background-color: #e0e0e0;\">AGREGAR CANDIDATO</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/agregarCandidato.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
