/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-06-28 12:14:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ya_002dvoto;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ya_002dvoto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Ya Votó</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- FontAwesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS global -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/Style.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .card-ya-voto {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 32px;\r\n");
      out.write("            padding: 60px 45px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: var(--shadow-xl);\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("            animation: fadeInUp .6s ease;\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon-warning {\r\n");
      out.write("            width: 130px;\r\n");
      out.write("            height: 130px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            background: linear-gradient(135deg, #f59e0b, #d97706);\r\n");
      out.write("            box-shadow: 0 15px 35px rgba(245,158,11,.35);\r\n");
      out.write("            animation: float 4s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon-warning i {\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .titulo {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subtitulo {\r\n");
      out.write("            color: var(--mid);\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .datos {\r\n");
      out.write("            background: var(--lighter);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            padding: 20px 25px;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .datos h5 {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .datos p {\r\n");
      out.write("            color: var(--mid);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alerta-voto-realizado {\r\n");
      out.write("            background: #fef3c7;\r\n");
      out.write("            border: 1px solid #fbbf24;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            color: #92400e;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-salir {\r\n");
      out.write("            height: 58px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            background: linear-gradient(135deg, #64748b, #475569);\r\n");
      out.write("            color: white;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(100,116,139,.3);\r\n");
      out.write("            transition: .3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-salir:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 15px 30px rgba(100,116,139,.4);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header-primary\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                <i class=\"fas fa-vote-yea me-2\"></i>\r\n");
      out.write("                Sistema Electoral Nacional\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main-content\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card-ya-voto\">\r\n");
      out.write("\r\n");
      out.write("            <!-- ÍCONO -->\r\n");
      out.write("            <div class=\"icon-warning\">\r\n");
      out.write("                <i class=\"fas fa-check-double\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- TÍTULO -->\r\n");
      out.write("            <h1 class=\"titulo\">Voto Registrado</h1>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"subtitulo\">\r\n");
      out.write("                El ciudadano ya realizó su voto anteriormente en el sistema electoral.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <!-- DATOS dinámicos desde sesión -->\r\n");
      out.write("            <div class=\"datos\">\r\n");
      out.write("                <h5>");
      out.print(
                    session.getAttribute("nombrePersona") != null
                        ? session.getAttribute("nombrePersona")
                        : "Ciudadano"
                );
      out.write("</h5>\r\n");
      out.write("                <p>DNI: ");
      out.print(
                    session.getAttribute("dniPersona") != null
                        ? session.getAttribute("dniPersona")
                        : "-"
                );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ALERTA -->\r\n");
      out.write("            <div class=\"alerta-voto-realizado\">\r\n");
      out.write("                <i class=\"fas fa-circle-info me-2\"></i>\r\n");
      out.write("                Este ciudadano ya emitió su voto.\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- BOTÓN -->\r\n");
      out.write("            <button class=\"btn btn-salir\"\r\n");
      out.write("                    onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/home/home.jsp'\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left me-2\"></i>\r\n");
      out.write("                VOLVER\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
