services:

  padron:
    container_name: padron
    image: sebastianpzz/sistema-de-elecciones:padron
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - red-backend

  db:
    image: sebastianpzz/sistema-de-elecciones:db
    container_name: padron-db
    restart: always

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - red-backend

networks:
  red-backend:
    driver: bridge

volumes:
  mysql_data: