/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-06-24 21:43:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Voto Confirmado</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- FontAwesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        .card-confirmacion{\r\n");
      out.write("\r\n");
      out.write("            background:white;\r\n");
      out.write("            border-radius:32px;\r\n");
      out.write("            padding:60px 45px;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            box-shadow:var(--shadow-xl);\r\n");
      out.write("            border:1px solid var(--border);\r\n");
      out.write("\r\n");
      out.write("            animation:fadeInUp .6s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icono-confirmado{\r\n");
      out.write("\r\n");
      out.write("            width:130px;\r\n");
      out.write("            height:130px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("\r\n");
      out.write("            background:linear-gradient(135deg,#22c55e,#16a34a);\r\n");
      out.write("\r\n");
      out.write("            box-shadow:0 15px 35px rgba(34,197,94,.35);\r\n");
      out.write("\r\n");
      out.write("            animation:float 4s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icono-confirmado i{\r\n");
      out.write("\r\n");
      out.write("            color:white;\r\n");
      out.write("            font-size:60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .titulo-confirmado{\r\n");
      out.write("\r\n");
      out.write("            font-size:2.3rem;\r\n");
      out.write("            font-weight:800;\r\n");
      out.write("            color:var(--dark);\r\n");
      out.write("            margin-bottom:15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .texto-confirmado{\r\n");
      out.write("\r\n");
      out.write("            color:var(--mid);\r\n");
      out.write("            font-size:1rem;\r\n");
      out.write("            margin-bottom:35px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-candidato-voto{\r\n");
      out.write("\r\n");
      out.write("            background:var(--lighter);\r\n");
      out.write("            border-radius:20px;\r\n");
      out.write("            padding:25px;\r\n");
      out.write("            margin-bottom:35px;\r\n");
      out.write("\r\n");
      out.write("            border:1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .foto-mini{\r\n");
      out.write("\r\n");
      out.write("            width:90px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            margin-bottom:15px;\r\n");
      out.write("\r\n");
      out.write("            border:4px solid white;\r\n");
      out.write("\r\n");
      out.write("            box-shadow:var(--shadow);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .foto-mini img{\r\n");
      out.write("\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            object-fit:cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-inicio{\r\n");
      out.write("\r\n");
      out.write("            height:58px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:16px;\r\n");
      out.write("\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            letter-spacing:1px;\r\n");
      out.write("\r\n");
      out.write("            background:linear-gradient(135deg,var(--primary),var(--accent));\r\n");
      out.write("            color:white;\r\n");
      out.write("\r\n");
      out.write("            box-shadow:0 10px 25px rgba(26,86,219,.3);\r\n");
      out.write("\r\n");
      out.write("            transition:.3s;\r\n");
      out.write("\r\n");
      out.write("            position:relative;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-inicio::after{\r\n");
      out.write("\r\n");
      out.write("            content:\"\";\r\n");
      out.write("\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            top:0;\r\n");
      out.write("            left:-100%;\r\n");
      out.write("\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:100%;\r\n");
      out.write("\r\n");
      out.write("            background:linear-gradient(\r\n");
      out.write("                90deg,\r\n");
      out.write("                transparent,\r\n");
      out.write("                rgba(255,255,255,.25),\r\n");
      out.write("                transparent\r\n");
      out.write("            );\r\n");
      out.write("\r\n");
      out.write("            transition:.6s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-inicio:hover::after{\r\n");
      out.write("            left:100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-inicio:hover{\r\n");
      out.write("\r\n");
      out.write("            transform:translateY(-3px);\r\n");
      out.write("\r\n");
      out.write("            box-shadow:0 15px 30px rgba(26,86,219,.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header-primary\">\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                    <i class=\"fas fa-vote-yea me-2\"></i>\r\n");
      out.write("                    Sistema Electoral Nacional\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- MAIN -->\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-confirmacion\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- ICONO -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"icono-confirmado\">\r\n");
      out.write("\r\n");
      out.write("                            <i class=\"fas fa-check\"></i>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- TITULO -->\r\n");
      out.write("\r\n");
      out.write("                        <h1 class=\"titulo-confirmado\">\r\n");
      out.write("                            ¡Voto Registrado!\r\n");
      out.write("                        </h1>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"texto-confirmado\">\r\n");
      out.write("\r\n");
      out.write("                            Su voto fue emitido correctamente y quedó registrado en el sistema electoral nacional.\r\n");
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <!-- CANDIDATO -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"card-candidato-voto\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"foto-mini\">\r\n");
      out.write("\r\n");
      out.write("                                <img id=\"fotoCandidato\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <h3 id=\"nombreCandidato\"></h3>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"text-muted mb-0\" id=\"partidoCandidato\"></p>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- BOTON -->\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"btn btn-inicio w-100\"\r\n");
      out.write("                         onclick=\"window.location.href='inicio.html'\">\r\n");
      out.write("\r\n");
      out.write("                            <i class=\"fas fa-home me-2\"></i>\r\n");
      out.write("                            VOLVER AL INICIO\r\n");
      out.write("\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <script>\r\n");
      out.write("\r\n");
      out.write("                           const params = new URLSearchParams(window.location.search);\r\n");
      out.write("\r\n");
      out.write("                           const candidato = params.get('candidato');\r\n");
      out.write("                           const partido = params.get('partido');\r\n");
      out.write("                           const foto = params.get('foto');\r\n");
      out.write("\r\n");
      out.write("                           document.getElementById('nombreCandidato').innerText =\r\n");
      out.write("                           candidato;\r\n");
      out.write("\r\n");
      out.write("                           document.getElementById('partidoCandidato').innerText =\r\n");
      out.write("                           partido;\r\n");
      out.write("\r\n");
      out.write("                           document.getElementById('fotoCandidato').src =\r\n");
      out.write("                           foto;\r\n");
      out.write("\r\n");
      out.write("                         </script>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
