/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-06-28 17:32:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Panel Administrativo</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/Style.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script>var contextPath = '");
      out.print(request.getContextPath());
      out.write("';</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* ── Skeleton loader ─────────────────────────────── */\r\n");
      out.write(".skeleton {\r\n");
      out.write("    background: linear-gradient(90deg, #e2e8f0 25%, #f1f5f9 50%, #e2e8f0 75%);\r\n");
      out.write("    background-size: 200% 100%;\r\n");
      out.write("    animation: shimmer 1.4s infinite;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("@keyframes shimmer {\r\n");
      out.write("    0%   { background-position: 200% 0; }\r\n");
      out.write("    100% { background-position: -200% 0; }\r\n");
      out.write("}\r\n");
      out.write(".sk-numero  { width: 80px;  height: 32px; }\r\n");
      out.write(".sk-texto   { width: 120px; height: 16px; margin-top: 6px; }\r\n");
      out.write(".sk-line    { width: 100%;  height: 18px; margin-bottom: 10px; }\r\n");
      out.write(".sk-circle  { width: 220px; height: 220px; border-radius: 50%; }\r\n");
      out.write(".sk-ganador-nombre  { width: 180px; height: 28px; margin: 12px auto; }\r\n");
      out.write(".sk-ganador-partido { width: 130px; height: 16px; margin: 0 auto 16px; }\r\n");
      out.write(".sk-stat    { width: 60px;  height: 28px; }\r\n");
      out.write("\r\n");
      out.write("/* ── Fade-in al revelar contenido ────────────────── */\r\n");
      out.write(".fade-in {\r\n");
      out.write("    animation: fadeInUp .5s ease forwards;\r\n");
      out.write("}\r\n");
      out.write("@keyframes fadeInUp {\r\n");
      out.write("    from { opacity: 0; transform: translateY(12px); }\r\n");
      out.write("    to   { opacity: 1; transform: translateY(0); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ── Indicador de refresh ────────────────────────── */\r\n");
      out.write(".refresh-badge {\r\n");
      out.write("    font-size: 0.75rem;\r\n");
      out.write("    color: #64748b;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 6px;\r\n");
      out.write("}\r\n");
      out.write(".refresh-dot {\r\n");
      out.write("    width: 8px;\r\n");
      out.write("    height: 8px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    background: #22c55e;\r\n");
      out.write("    animation: pulse-dot 2s infinite;\r\n");
      out.write("}\r\n");
      out.write("@keyframes pulse-dot {\r\n");
      out.write("    0%, 100% { opacity: 1; transform: scale(1); }\r\n");
      out.write("    50%       { opacity: .5; transform: scale(1.4); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ── Contador de próximo refresh ─────────────────── */\r\n");
      out.write(".countdown-text {\r\n");
      out.write("    font-size: 0.7rem;\r\n");
      out.write("    color: #94a3b8;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ══════════════ HEADER ══════════════ -->\r\n");
      out.write("<header class=\"header-primary\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container-fluid px-4\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                <i class=\"fas fa-shield-halved me-3\"></i>\r\n");
      out.write("                Panel Administrativo\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"d-flex gap-2\">\r\n");
      out.write("                <button class=\"btn btn-logout\" id=\"btnLogout\">\r\n");
      out.write("                    <i class=\"fas fa-right-from-bracket me-2\"></i>\r\n");
      out.write("                    Cerrar Sesión\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- ══════════════ MAIN ══════════════ -->\r\n");
      out.write("<main class=\"main-content\">\r\n");
      out.write("    <div class=\"container px-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-5 mt-4 d-flex justify-content-between align-items-start flex-wrap gap-3\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1 class=\"titulo-dashboard\">Dashboard Electoral</h1>\r\n");
      out.write("                <p class=\"subtitulo\">Control y gestión del sistema electoral nacional</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"d-flex flex-column align-items-end gap-1\">\r\n");
      out.write("                <div class=\"refresh-badge\">\r\n");
      out.write("                    <span class=\"refresh-dot\"></span>\r\n");
      out.write("                    Actualizando en tiempo real\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"countdown-text\" id=\"countdownText\">Próxima actualización en 30s</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ══ MÉTRICAS ══ -->\r\n");
      out.write("        <div class=\"row g-4 mb-5 row-metricas\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                <div class=\"card-metrica border-blue\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"numero\" id=\"totalPadron\">\r\n");
      out.write("                                <span class=\"skeleton sk-numero\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"texto\">Total en Padrón</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box blue\"><i class=\"fas fa-users\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                <div class=\"card-metrica border-green\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"numero\" id=\"habilitados\">\r\n");
      out.write("                                <span class=\"skeleton sk-numero\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"texto\">Habilitados para Votar</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box green\"><i class=\"fas fa-square-check\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                <div class=\"card-metrica border-orange\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"numero\" id=\"votosEmitidos\">\r\n");
      out.write("                                <span class=\"skeleton sk-numero\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"texto\">Votos Emitidos</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box icon-orange\"><i class=\"fas fa-check-to-slot\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                <div class=\"card-metrica border-red\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"numero\" id=\"deshabilitados\">\r\n");
      out.write("                                <span class=\"skeleton sk-numero\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"texto\">Deshabilitados</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box red\"><i class=\"fas fa-user-slash\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                <div class=\"card-metrica border-cyan\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"numero\" id=\"equiposActivos\">\r\n");
      out.write("                                <span class=\"skeleton sk-numero\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"texto\">Equipos Activos</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box cyan\"><i class=\"fas fa-laptop\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                <div class=\"card-metrica border-purple\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"numero\" id=\"participacion\">\r\n");
      out.write("                                <span class=\"skeleton sk-numero\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"texto\">Participación</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box purple\"><i class=\"fas fa-chart-pie\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ══ RESULTADOS + GANADOR ══ -->\r\n");
      out.write("        <div class=\"row g-4 mb-5\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Gráfico de torta -->\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("                <div class=\"card-custom\">\r\n");
      out.write("                    <h3>Resultados en Tiempo Real</h3>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Skeleton gráfico -->\r\n");
      out.write("                    <div id=\"skeletonGrafico\" class=\"d-flex justify-content-center mb-4\">\r\n");
      out.write("                        <span class=\"skeleton sk-circle\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"skeletonLista\">\r\n");
      out.write("                        <span class=\"skeleton sk-line d-block\"></span>\r\n");
      out.write("                        <span class=\"skeleton sk-line d-block\"></span>\r\n");
      out.write("                        <span class=\"skeleton sk-line d-block\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Contenido real -->\r\n");
      out.write("                    <div id=\"contenidoGrafico\" style=\"display:none;\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-center mb-4\">\r\n");
      out.write("                            <div class=\"grafico-circular\" id=\"graficoCircular\">\r\n");
      out.write("                                <div class=\"centro-grafico\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"listaResultados\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Ganador -->\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("                <div class=\"card-custom\">\r\n");
      out.write("                    <div class=\"badge-top\">Candidato en Primer Lugar</div>\r\n");
      out.write("                    <div class=\"icono-ganador\">\r\n");
      out.write("                        <i class=\"fas fa-trophy\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Skeleton ganador -->\r\n");
      out.write("                    <div id=\"skeletonGanador\" class=\"text-center\">\r\n");
      out.write("                        <span class=\"skeleton sk-ganador-nombre d-block\"></span>\r\n");
      out.write("                        <span class=\"skeleton sk-ganador-partido d-block\"></span>\r\n");
      out.write("                        <div class=\"row mt-3\">\r\n");
      out.write("                            <div class=\"col-6 text-center\">\r\n");
      out.write("                                <div class=\"dato\">Total de Votos</div>\r\n");
      out.write("                                <span class=\"skeleton sk-stat d-inline-block mt-1\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6 text-center\">\r\n");
      out.write("                                <div class=\"dato\">Porcentaje</div>\r\n");
      out.write("                                <span class=\"skeleton sk-stat d-inline-block mt-1\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Contenido real ganador -->\r\n");
      out.write("                    <div id=\"contenidoGanador\" style=\"display:none;\">\r\n");
      out.write("                        <div class=\"ganador-nombre\" id=\"ganadorNombre\"></div>\r\n");
      out.write("                        <div class=\"ganador-partido\" id=\"ganadorPartido\"></div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-6\">\r\n");
      out.write("                                <div class=\"dato\">Total de Votos</div>\r\n");
      out.write("                                <div class=\"valor text-blue\" id=\"ganadorVotos\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6\">\r\n");
      out.write("                                <div class=\"dato\">Porcentaje</div>\r\n");
      out.write("                                <div class=\"valor text-green\" id=\"ganadorPorcentaje\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"alert-victoria\" id=\"alertaVentaja\">\r\n");
      out.write("                            <i class=\"fas fa-arrow-trend-up me-2\"></i>\r\n");
      out.write("                            <span id=\"textoVentaja\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ══ GESTIÓN DEL SISTEMA ══ -->\r\n");
      out.write("        <h2 class=\"titulo-seccion\">Gestión del Sistema</h2>\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-6 mb-4\">\r\n");
      out.write("                <a href=\"/gestion-equipos/gestion-equipos.jsp\" class=\"text-decoration-none d-block card-clickable\">\r\n");
      out.write("                    <div class=\"card-action action-purple\">\r\n");
      out.write("                        <div class=\"icon-action purple\">\r\n");
      out.write("                            <i class=\"fas fa-computer\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5>Gestión de Equipos</h5>\r\n");
      out.write("                        <p>Control de PCs por MAC Address</p>\r\n");
      out.write("                        <div class=\"flecha\"><i class=\"fas fa-chevron-right\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-6 col-md-6 mb-4\">\r\n");
      out.write("                <a href=\"/gestion-candidatos/gestion-candidatos.jsp\" class=\"text-decoration-none d-block card-clickable\">\r\n");
      out.write("                    <div class=\"card-action action-orange\">\r\n");
      out.write("                        <div class=\"icon-action orange\">\r\n");
      out.write("                            <i class=\"fas fa-users\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5>Gestión de Candidatos</h5>\r\n");
      out.write("                        <p>Administrar candidatos de la boleta electoral</p>\r\n");
      out.write("                        <div class=\"flecha\"><i class=\"fas fa-chevron-right\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts al final del body — en este orden -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/dashboard.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/loginAdmin.js?v=4\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
