/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-06-27 22:59:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.gestion_002dequipos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gestion_002dequipos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Control de Equipos de Votación</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<header class=\"header-primary\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: #0d1b2a;\">\r\n");
      out.write("        <div class=\"container-fluid px-4\">\r\n");
      out.write("            <a class=\"navbar-brand fw-bold text-warning\" href=\"dashboard.html\">\r\n");
      out.write("                <i class=\"fas fa-th-large me-3\"></i>\r\n");
      out.write("                Panel Administrativo Electoral\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main-content py-4\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("            <a href=\"dashboard.html\" class=\"btn btn-outline-primary btn-sm rounded-2 px-3\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left me-2\"></i> VOLVER AL DASHBOARD\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1 class=\"h3 mb-1 fw-bold text-dark\">Control de Equipos de Votación</h1>\r\n");
      out.write("                <p class=\"text-muted mb-0\" style=\"font-size: 0.9rem;\">Gestione los equipos habilitados por MAC Address</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"btn btn-primary px-4 fw-medium shadow-sm d-inline-flex align-items-center rounded-3\" data-bs-toggle=\"modal\" data-bs-target=\"#modalEquipo\">\r\n");
      out.write("                <i class=\"fas fa-plus me-2\"></i> AGREGAR EQUIPO\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card border-0 shadow-sm rounded-4 p-4 mb-4 bg-white\">\r\n");
      out.write("            <div class=\"d-flex flex-column gap-4\" id=\"contenedor-equipos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"alert alert-info border-0 shadow-sm rounded-3 d-flex align-items-start gap-3 p-3\" role=\"alert\" style=\"background-color: #e0f2fe; border-left: 4px solid #0ea5e9 !important;\">\r\n");
      out.write("            <div class=\"text-info fs-5 mt-0\"><i class=\"fas fa-info-circle text-primary\"></i></div>\r\n");
      out.write("            <div style=\"font-size: 0.88rem; color: #0369a1; line-height: 1.5;\">\r\n");
      out.write("                <strong>Información:</strong> Lista de terminales actualmente registradas en la red del sistema electoral. Cada equipo está identificado de manera única por su dirección física de red (MAC Address).\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"modalEquipo\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" style=\"max-width: 480px;\">\r\n");
      out.write("        <div class=\"modal-content border-0 shadow-lg rounded-3 p-4 bg-white\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-header border-0 p-0 mb-4\">\r\n");
      out.write("                <h4 class=\"modal-title fw-bold text-dark\" id=\"modalEquipoLabel\" style=\"font-size: 1.3rem;\">Agregar Nuevo Equipo de Votación</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-body p-0 mb-4\">\r\n");
      out.write("                <form id=\"formEquipo\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"equipoId\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-4\">\r\n");
      out.write("                        <label class=\"form-label text-muted small fw-bold\">Nombre del Equipo</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control px-3 py-2 border rounded\" id=\"nombreMac\" placeholder=\"Ej: PC Mesa 1\" style=\"font-size: 0.95rem;\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-2\">\r\n");
      out.write("                        <label class=\"form-label text-muted small fw-bold\">MAC Address</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control px-3 py-2 border rounded font-monospace\" id=\"macAddress\" placeholder=\"Ej: 00:1B:44:11:3A:B7\" style=\"font-size: 0.95rem;\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"text-muted d-block ps-1\" style=\"font-size: 0.75rem;\">Identificador único físico del equipo.</small>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-footer border-0 p-0 d-flex justify-content-end gap-3\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link text-decoration-none fw-semibold text-primary px-2\" data-bs-dismiss=\"modal\" style=\"font-size: 0.88rem; letter-spacing: 0.5px;\">CANCELAR</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary px-4 py-2 fw-semibold border-0 rounded shadow-sm\" id=\"btnGuardarEquipo\" style=\"font-size: 0.88rem; letter-spacing: 0.5px;\">AGREGAR EQUIPO</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var contextPath = '");
      out.print( request.getContextPath() );
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/scripts/equiposAdmin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
